const ROTAS = {
    "ROTA 1": {
        id:"ROTA 1",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota: '1. (Manhã- ida) – Sítio Pendencia, Sítio Engenho Velho, Sítio Cajueiro,\
         Rua Projetada, Sitio Portelinha, Novo Pernambuco.\
         2. (Manhã volta - Tarde ida) – Novo Pernambuco, Sítio Silvestre, Sítio Cajueiro, Sitio Mata Verde, Sítio Engenho velho, Sitio Barbalho,\
         Sítio Pendencia, Sítio Mata verde, Novo Pernambuco, Sítio Silvestre, Sítio Tapoio, Novo Pernambuco. 3. (Tarde volta- Noite ida) – Novo Pernambuco, Sítio Tapoio, Sítio Silvestre, Sítio Mata Verde, Sítio Barbalho, Sítio Tamboril, Sítio Pendencia, Sítio Santa Rita, Sítio Mata Verde, Sítio Brejo, Sítio Silvestre, Sítio Cacimbinha, Novo Pernambuco. 4. (Noite Volta) – Novo Pernambuco, Sítio Cacimbinha, Sítio Silvestre, Sítio Brejo, Sítio Santa Rita, \
         Sítio Mata Verde, Sítio Pendencia'
        ,
        kmPavimentado:13.571,
        kmNaoPavimentado: 78.71,
        valorFixo:2426.15,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 2": {
        id:"ROTA 2",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota: '1. (Manhã- ida) –  Sítio Cacimbinha, Sítio Pajeú, Sítio Canastra, Sítio Cacimbinhha, Sítio Colonia 2, Novo Pernambuco. 2. (Manhã- volta - Tarde ida) –  Sítio Novo Pernambuco, Sítio Cacimbinha, Sítio Pajeú, Sítio Cacimbinha, Sítio Colonia 2, Novo Pernambuco. 3. (Tarde- Volta) – Sítio Cacimbinha, Sítio Pajeú, Sítio Colonia 2.',
        kmPavimentado:2.872,
        kmNaoPavimentado: 63.238,
        valorFixo:2505.66,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 3": {
        id:"ROTA 3",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Novo Pernambuco, Sítio Jardim, Sítio Quintas, Sítio Barreiros, Sítio Manoel Soares, Ibitiranga p/ Carnaiba.',
        kmPavimentado:39.482,
        kmNaoPavimentado:50.130,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 4": {
        id:"ROTA 4",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Jardim de Fora, Sítio Jardim Carnaiba, Sítio Quintas, Sítio Barreiros, Sítio Jatobá, Sítio Manoel Soares, Sítio Bem Te Vi, Sítio Manoel Soares, Sítio Be-te-vi, Sítio Jatobá.',
        kmPavimentado:0,
        kmNaoPavimentado:59.748,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 5": {
        id:"ROTA 5",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Antas, Sítio Caúira, Sítio Antas, Sítio Bem Ti Vi, Sítio Jatoba. 2. (Manhã- Volta Tarde Ida) – Sítio Jatoba, Sítio Bem Ti Vi, Sítio Caiura, Sítio Antas, Sítio Bem Ti Vi, Sítio Jatoba. 3. (Tarde Volta) – Sítio Jatoba, Sítio Bem Ti Vi, Sítio Caiura, Sitio Antas.',
        kmPavimentado:0,
        kmNaoPavimentado:41.355,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 6": {
        id:"ROTA 6",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Jardim, Sítio Quintas, Sítio Barreiros, Sítio Brejo, Sítio Alegre, Sítio Jatoba. 2. (Manhã- volta - Tarde ida) –Sítio Jatoba, Sítio Alegre,Sítio Barreiros, Sítio Brejo, Sítio Quintas, Sítio Jardim, Sítio Quintas, Sítio Brejo, Sítio Barreiros, Sítio Jatobá. 1. (Tarde Volta) – Sítio Barreiros, Sítio Brejo, Sítio Barreiros, Sítio Quintas, Sítio Jardim.',
        kmPavimentado:0,
        kmNaoPavimentado:42.128,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,  
    },
    "ROTA 7": {
        id:"ROTA 7",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Alto Vermelho, Sítio Serrinha, Sítio Caiçara, Sítio Minador, Sítio Cachoeira Cancão, Alto Vermelho, Ibitiranga. 2. (Manhã- volta - Tarde ida) – Ibitiranga, Alto Vermelho, Sítio Cachoeira do Cancão, Sítio Serrinha, Sítio Minador, Sítio Serrinha,Sítio Caiçara, Alto Vermelho. 3. (Tarde Volta) – Sítio Caiçara, Sítio Minador, Sítio Serrinha, Alto Vemelho, Ibitiranga.',
        kmPavimentado:3.758,
        kmNaoPavimentado:64.026,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 8": {
        id:"ROTA 8",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Riacho Fundo, Sítio Pitombeira, Sítio Colonia, Ibitiranga. 2. (Manhã volta Tarde ida) – Ibitiranga, Sítio Pitombeira, Sítio Riacho Fundo, Sítio Colonia, Ibitiranga. 3. (Tarde Volta) – Ibitiranga, Colonia, Pitombeira.',
        kmPavimentado:0,
        kmNaoPavimentado:38.689,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 9": {
        id:"ROTA 9",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Riacho da Colonia, Sítio Caiçara, Sítio Curral Velho, Sítio Serrinha, Sítio Curral Velho.',
        kmPavimentado:0,
        kmNaoPavimentado:33.698,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 10": {
        id:"ROTA 10",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Curral Velho, Sítio Serrinha, Sítio Curral Velho, Sítio Caiçara, Ibitiranga. 2. (Manhã volta - Tarde ida) – Ibitiranga, Curral Velho, Sítio Serrinha, Sítio Curral Velho, Sítio Caiçara, Sítio Serrinha, Sítio Curral Velho, Ibitiranga. 3. (Tarde Volta) –  Sítio Curral Velho, Sítio Serrinha, Sítio Curral Velho, Ibitiranga.',
        kmPavimentado:4.628,
        kmNaoPavimentado:59.855,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 11": {
        id:"ROTA 11",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Roça de Dentro, Sítio Santo Antonio. ITÃ.',
        kmPavimentado:24.474,
        kmNaoPavimentado:34.684,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 12": {
        id:"ROTA 12",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Gameleira, Sítio Serra do Urubu, Sítio Travessão, Sítio Brejo de Dentro.',
        kmPavimentado:0,
        kmNaoPavimentado:47.358,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 13": {
        id:"ROTA 13",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –   Sítio Travessão do Caroá, Sítio Caxi, Sítio Barreiro do Fabiano, Sítio Pitombeira, Sítio Chapada, Sítio Lagoa do Caroá. 2. (Manhã- volta Tarde ida) – Sítio Lagoa do Caroá, Sítio Chapada, Sítio Pitombeira, Sítio Barreiro do Fabiano, Sítio Caxi, Sítio Travessão do Caroá, Sítio Travessão, Sítio Brejo de Dentro, Sítio Abelha, Sítio Gameleira, Sítio Chapada de Lagoa, Sítio Lagoa do Caroá.  3. (Tarde Volta) – Sítio Lagoa do Caroá, Sítio Chapada de Lagoa, Sítio Travessão, Sítio Gameleira, Sítio Travessão.',
        kmPavimentado:0,
        kmNaoPavimentado:103.915,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 14": {
        id:"ROTA 14",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Capim de Planta, Sítio Travessão, Sítio Abelha, Sítio Gameleira, Sítio Serra do Urubu, Sítio Gameleira, Sítio Travessão, Sítio Lagoa do Caroá. 2. (Manhã- volta Tarde ida) – Lagoa do Caroá, Sítio Travessão, Sítio Gameleira, Sítio Serra do Urubu, Sítio Gameleira, Sítio Abelha, Sítio Travessão, Sitio Capim de planta, Sítio Barreiros do Fabiano, Sítio Travesssão. 3. (Tarde Volta) – Sítio Lagoa do Caroá, Sítio Barreiro do Fabiano, Sítio Travessão.',
        kmPavimentado:0,
        kmNaoPavimentado:82.033,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 15": {
        id:"ROTA 15",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Malhada, Sítio Macammbinho, Sítio Serrinha, Sítio Carnaiba Velha, Sítio Carnaiba, Sítio Alto da Santa Luzia, Carnaiba. 2. (Manhã-volta Tarde ida) – Carnaiba, Sítio Alto da Santa Luzia, Sítio Carnaiba Velha, Sítio Serrinha, Sítio Mucambinho, Sítio Malhada, Carnaiba. 3. (Tarde volta) – Carnaiba, Sítio Carnaiba Velha, Sítio Serrinha, Sítio Mucambinho, Sítio Malhada.',
        kmPavimentado:14.542,
        kmNaoPavimentado:74.790,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 16": {
        id:"ROTA 16",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Cabelo, Sítio Caxetes, Sítio Leites, Sítio Poço do Viado, Sítio Itã, Sítio Leitão, Sítio Caxetes, Sítio Cachoeira. 2. (Manhã-volta Tarde ida) –  Sítio poço do viado, Sítio Cabelo, Sítio Caxetes, Sítio Leites, Sítio Poço do Viado, Sítio Itã, Sítio Leitão, Sítio Caxetes, Sítio Cachoeira 3. (Tarde volta) – Sítio Cabelo, Sítio Caxetes, Sítio Leites, Sítio Poço do Viado, Sítio Itã, Sítio Leitão, Sítio Caxetes, Sítio Cachoeira',
        kmPavimentado:13.601,
        kmNaoPavimentado:31.837 ,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 17": {
        id:"ROTA 17",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Travessão do Caroá, Sítio Capim de Planta, Sítio Pau Darco, Sítio Vila Delmiro, Siítio Serra Branca.  2. (Manhã-volta Tarde ida) –  Sítio Serra Branca, Sítio Vila Delmiro, Sítio Pau Darco, Sítio Capim de Planta, Sítio Travessão do Caroá. 3. (Tarde Volta) -  Sítio Travessão do Caroá, Sítio Capim de Planta, Sítio Pau Darco, Sítio Vila Delmiro, Siítio Serra Branca.',
        kmPavimentado:2.940,
        kmNaoPavimentado:95.758,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 18": {
        id:"ROTA 18",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Matinha, Sítio Olho D agua, Sítio Chico Pereira, Sítio Tamboril.',
        kmPavimentado:0,
        kmNaoPavimentado:27.910,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 19": {
        id:"ROTA 19",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Cacimba Velho, Sítio Açude do Caroá, Serra Branca. 2. (Manhã-volta Tarde ida) – Serra Branca, Sítio Açude do Caroá, Sítio Cacimba Velho, Açude do Caroá, Sítio Cacimba Velha, Serra Branca. 3. (Tarde Volta) - Serra Branca, Sítio Açude do Caroá, Cacimba Velha.',
        kmPavimentado:6.860,
        kmNaoPavimentado:51.494,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 20": {
        id:"ROTA 20",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Barreiro, Sítio Canastra, Sítio Pitombeira, Sítio Saquim, Sítio Lagoa do Caroá, Sítio Capím de planta, Serra Branca.  2. (Manhã-volta Tarde ida) – Serra Branca, Sítio Caim de Planta, Sítio Caroá, Sítio Saquim, Sítio Pitombeira, Sítio Barreiro, Sítio Canastra, Sítio Capim de Planta, Sítio Lagoa do Caroá, Serra Branca.  3. (Tarde Volta) - Sítio Barreiro Fabiano, Sítio Canastram, Sítio Pitombeira, Sítio Capim de Planta, Serra Branca.',
        kmPavimentado:6.620,
        kmNaoPavimentado:92.476,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
       
    },
    "ROTA 21": {
        id:"ROTA 21",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Riacho Fundo, Sítio Saco dos Queiroz, Sítio Roça de Dentro.',
        kmPavimentado:0.778,
        kmNaoPavimentado:28.036,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 22": {
        id:"ROTA 22",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Lagoa dos Campos, Sítio Marias Pretas, Sítio Varzinha, Carnaiba.  2. (Manhã-volta Tarde ida) –  Carnaiba, Sítio Lagoa dos Campos, Sítio Marias Pretas, Sítio Lagoas dos Campos, Carnaiba. 3. (Tarde Volta) -  Sítio Lagoa dos Campos, Sítio Varzinha, Sítio Carnaiba.',
        kmPavimentado:15.835,
        kmNaoPavimentado:40.995,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 23": {
        id:"ROTA 23",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Pinhacozinho, Sítio Poço Grande, Sítio Caiçara, Carnaiba.  2. (Manhã-volta Tarde ida) –  Carnaiba, Sítio Caiçara, Sítio Poço Grande, Sítio Pinhacozinho, Sítio Poço Grande, Caiçara, Carnaiba.. 3. (Tarde Volta) - Carnaiba, Sítio Caiçara, Sítio Poço Grande.',
        kmPavimentado:57.666,
        kmNaoPavimentado:15.580,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 24": {
        id:"ROTA 24",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Lajinha, Sítio Poço Grande, Carnaiba. 2. (Manhã-volta Tarde ida) –  Carnaiba, Sitio Poço Grande, Sítio Lajinha, Sítio Poço Grande, Sítio Lajinha, Carnaiba. 3. (Tarde Volta) -  Carnaiba, Sítio Laranjinha, Sítio Poço Grande.',
        kmPavimentado:35.793,
        kmNaoPavimentado:47.824,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 25": {
        id:"ROTA 25",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Serrote Verde, Sítio Inveja, Serra Branca. 2. (Manhã-volta Tarde ida) – Serra Branca, Sítio Inveja, Sítio Serrote Verde  Serra Branca . 3. (Tarde Volta) - Serra Branca, Sítio Inveja, Sítio Serrote Verde.',
        kmPavimentado:5.808,
        kmNaoPavimentado:46.672,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 26": {
        id:"ROTA 26",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Riacho do Peixe, Sítio Capim Grosso. Sítio São Geraldo, Carnaiba 2. (Manhã-volta Tarde ida) – Carnaiba, Sítio São Geraldo, Sítio Capim Grosso, Sítio Riacho do Peixe,  Sítio Riacho do Peixe, Sítio Capim Grosso, Sítio São Geraldo, Sítio Alto Santa Luiza, Carnaiba. 3. (Tarde Volta) - Carnaiba, Sítio São Geraldo, Sítio Capim Grosso.',
        kmPavimentado:31.750,
        kmNaoPavimentado:8.490,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 27": {
        id:"ROTA 27",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Brejo, Sítio Bem Ti Vi, Sítio Travessão, Sítio Cauira, Sítio Manoel Soares, Sítio Poços, Ibitiranga. 2. (Manhã-volta Tarde ida) –  Ibitiranga, Sítio Poços, Sítio Manoel Soares,  Sítio Cauiea, Sítio Travessão, Sítio Bem Ti Vi, Sítio Brejo, Sítio Bem Ti Vi, Sítio Manoel Soares, Sítio Poços, Ibitiranga.. 3. (Tarde Volta) -   Ibitiranga, Sítio Poços, Sítio Manoel Soares,  Sítio Cauiea, Sítio Travessão, Sítio Bem Ti Vi, Sítio Brejo',
        kmPavimentado:6.532,
        kmNaoPavimentado:54.300,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 28": {
        id:"ROTA 28",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Alto Vermelho, Sítio Poços, Ibitiranga.  2. (Manhã-volta Tarde ida) – Ibitiranga, Sítio Poços, Sítio Alto Vermelho, Ibitiranga. 3. (Tarde Volta) - Ibitiranga, Sítio Poços.',
        kmPavimentado:4.224,
        kmNaoPavimentado:18.819,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 29": {
        id:"ROTA 29",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Radeador, Sítio Cacimba Velha, Sítio Radeador, Sítio Lagoa da Jurema, Carnaiba.  2. (Manhã-volta Tarde ida) – Carnaiba, Sítio Lagoa da Jurema, Sítio Radeador, Sítio Radeador, Sítio Lagoa da Jurema, Carnaiba. 3. (Tarde Volta) - Carnaiba, Sítio Lagoa da Jurema, Sítio Radeador.',
        kmPavimentado:18.420,
        kmNaoPavimentado:52.164,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 30": {
        id:"ROTA 30",
        condutor: "JOSÉ PATRIOTA DE MEDEIROS FILHO",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Rosilho, Sítio Lagoinha, Sítio Capim Grosso, Carnaiba.  2. (Manhã-volta Tarde ida) – Carnaiba, Sítio Capim Grosso, Sítio Lagoinha, Sítio Rosilho, Carnaiba. 3. (Tarde Volta) - Carnaiba, Sítio Capim Grosso, Sítio Lagoinha, Sítio Rosilho. ',
        kmPavimentado:72.582,
        kmNaoPavimentado:70.117,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 31": {
        id:"ROTA 31",
        condutor: "",
        tipo:'ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Afogados da Ingazeira, Itam, Carnaiba.  2.  (Tarde Volta) - Carnaiba, Itam, Afogados da Ingazeira',
        kmPavimentado:47.996,
        kmNaoPavimentado:0,
        valorFixo:4065.40692701771,
        valorKmPavimentado: 3.93805543727962,
        valorKmNaoPavimentado: 4.87922545286351,
    },
    "ROTA 32": {
        id:"ROTA 32",
        condutor: "",
        tipo:'ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Afogados da Ingazeira, Itam, Carnaiba.  2.  (Tarde Volta) - Carnaiba, Itam, Afogados da Ingazeira',
        kmPavimentado:47.996,
        kmNaoPavimentado:0,
        valorFixo:4065.40692701771,
        valorKmPavimentado: 3.93805543727962,
        valorKmNaoPavimentado: 4.87922545286351,
    },
    "ROTA 33": {
        id:"ROTA 33",
        condutor: "",
        tipo:'ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Afogados da Ingazeira, Itam, Carnaiba.  2.  (Tarde Volta) - Carnaiba, Itam, Afogados da Ingazeira',
        kmPavimentado:47.996,
        kmNaoPavimentado:0,
        valorFixo:4065.40692701771,
        valorKmPavimentado: 3.93805543727962,
        valorKmNaoPavimentado: 4.87922545286351,
    }
}
