const ROTAS = {
    "ROTA 1": {
        id:"ROTA 1",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota: '1. (Manhã- ida) – Sítio Pendencia, Sítio Engenho Velho, Sítio Cajueiro,\
         Rua Projetada, Sitio Portelinha, Novo Pernambuco.\
         2. (Manhã volta - Tarde ida) – Novo Pernambuco, Sítio Silvestre, Sítio Cajueiro, Sitio Mata Verde, Sítio Engenho velho, Sitio Barbalho,\
         Sítio Pendencia, Sítio Mata verde, Novo Pernambuco, Sítio Silvestre, Sítio Tapoio, Novo Pernambuco. 3. (Tarde volta- Noite ida) – Novo Pernambuco, Sítio Tapoio, Sítio Silvestre, Sítio Mata Verde, Sítio Barbalho, Sítio Tamboril, Sítio Pendencia, Sítio Santa Rita, Sítio Mata Verde, Sítio Brejo, Sítio Silvestre, Sítio Cacimbinha, Novo Pernambuco. 4. (Noite Volta) – Novo Pernambuco, Sítio Cacimbinha, Sítio Silvestre, Sítio Brejo, Sítio Santa Rita, \
         Sítio Mata Verde, Sítio Pendencia'
        ,
        kmPavimentado:13.571,
        kmNaoPavimentado: 78.71,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 2": {
        id:"ROTA 2",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota: '1. (Manhã- ida) –  Sítio Cacimbinha, Sítio Pajeú, Sítio Canastra, Sítio Cacimbinhha, Sítio Colonia 2, Novo Pernambuco. 2. (Manhã- volta - Tarde ida) –  Sítio Novo Pernambuco, Sítio Cacimbinha, Sítio Pajeú, Sítio Cacimbinha, Sítio Colonia 2, Novo Pernambuco. 3. (Tarde- Volta) – Sítio Cacimbinha, Sítio Pajeú, Sítio Colonia 2.',
        kmPavimentado:2.872,
        kmNaoPavimentado: 63.238,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 3": {
        id:"ROTA 3",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Novo Pernambuco, Sítio Jardim, Sítio Quintas, Sítio Barreiros, Sítio Manoel Soares, Ibitiranga p/ Carnaiba.',
        kmPavimentado:39.482,
        kmNaoPavimentado:50.130,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 4": {
        id:"ROTA 4",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Jardim de Fora, Sítio Jardim Carnaiba, Sítio Quintas, Sítio Barreiros, Sítio Jatobá, Sítio Manoel Soares, Sítio Bem Te Vi, Sítio Manoel Soares, Sítio Be-te-vi, Sítio Jatobá.',
        kmPavimentado:0,
        kmNaoPavimentado:59.748,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 5": {
        id:"ROTA 5",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Antas, Sítio Caúira, Sítio Antas, Sítio Bem Ti Vi, Sítio Jatoba. 2. (Manhã- Volta Tarde Ida) – Sítio Jatoba, Sítio Bem Ti Vi, Sítio Caiura, Sítio Antas, Sítio Bem Ti Vi, Sítio Jatoba. 3. (Tarde Volta) – Sítio Jatoba, Sítio Bem Ti Vi, Sítio Caiura, Sitio Antas.',
        kmPavimentado:0,
        kmNaoPavimentado:41.355,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 6": {
        id:"ROTA 6",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Jardim, Sítio Quintas, Sítio Barreiros, Sítio Brejo, Sítio Alegre, Sítio Jatoba. 2. (Manhã- volta - Tarde ida) –Sítio Jatoba, Sítio Alegre,Sítio Barreiros, Sítio Brejo, Sítio Quintas, Sítio Jardim, Sítio Quintas, Sítio Brejo, Sítio Barreiros, Sítio Jatobá. 1. (Tarde Volta) – Sítio Barreiros, Sítio Brejo, Sítio Barreiros, Sítio Quintas, Sítio Jardim.',
        kmPavimentado:0,
        kmNaoPavimentado:42.128,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,  
    },
    "ROTA 7": {
        id:"ROTA 7",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Alto Vermelho, Sítio Serrinha, Sítio Caiçara, Sítio Minador, Sítio Cachoeira Cancão, Alto Vermelho, Ibitiranga. 2. (Manhã- volta - Tarde ida) – Ibitiranga, Alto Vermelho, Sítio Cachoeira do Cancão, Sítio Serrinha, Sítio Minador, Sítio Serrinha,Sítio Caiçara, Alto Vermelho. 3. (Tarde Volta) – Sítio Caiçara, Sítio Minador, Sítio Serrinha, Alto Vemelho, Ibitiranga.',
        kmPavimentado:3.758,
        kmNaoPavimentado:64.026,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 8": {
        id:"ROTA 8",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Riacho Fundo, Sítio Pitombeira, Sítio Colonia, Ibitiranga. 2. (Manhã volta Tarde ida) – Ibitiranga, Sítio Pitombeira, Sítio Riacho Fundo, Sítio Colonia, Ibitiranga. 3. (Tarde Volta) – Ibitiranga, Colonia, Pitombeira.',
        kmPavimentado:0,
        kmNaoPavimentado:38.689,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 9": {
        id:"ROTA 9",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Riacho da Colonia, Sítio Caiçara, Sítio Curral Velho, Sítio Serrinha, Sítio Curral Velho.',
        kmPavimentado:0,
        kmNaoPavimentado:33.698,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 10": {
        id:"ROTA 10",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Curral Velho, Sítio Serrinha, Sítio Curral Velho, Sítio Caiçara, Ibitiranga. 2. (Manhã volta - Tarde ida) – Ibitiranga, Curral Velho, Sítio Serrinha, Sítio Curral Velho, Sítio Caiçara, Sítio Serrinha, Sítio Curral Velho, Ibitiranga. 3. (Tarde Volta) –  Sítio Curral Velho, Sítio Serrinha, Sítio Curral Velho, Ibitiranga.',
        kmPavimentado:4.628,
        kmNaoPavimentado:59.855,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 11": {
        id:"ROTA 11",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Roça de Dentro, Sítio Santo Antonio. ITÃ.',
        kmPavimentado:24.474,
        kmNaoPavimentado:34.684,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 12": {
        id:"ROTA 12",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Gameleira, Sítio Serra do Urubu, Sítio Travessão, Sítio Brejo de Dentro.',
        kmPavimentado:0,
        kmNaoPavimentado:47.358,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 13": {
        id:"ROTA 13",
        condutor: "",
        tipo:'MICRO-ONIBUS',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –   Sítio Travessão do Caroá, Sítio Caxi, Sítio Barreiro do Fabiano, Sítio Pitombeira, Sítio Chapada, Sítio Lagoa do Caroá. 2. (Manhã- volta Tarde ida) – Sítio Lagoa do Caroá, Sítio Chapada, Sítio Pitombeira, Sítio Barreiro do Fabiano, Sítio Caxi, Sítio Travessão do Caroá, Sítio Travessão, Sítio Brejo de Dentro, Sítio Abelha, Sítio Gameleira, Sítio Chapada de Lagoa, Sítio Lagoa do Caroá.  3. (Tarde Volta) – Sítio Lagoa do Caroá, Sítio Chapada de Lagoa, Sítio Travessão, Sítio Gameleira, Sítio Travessão.',
        kmPavimentado:0,
        kmNaoPavimentado:103.915,
        valorFixo:2987.4913857375,
        valorKmPavimentado: 2.8141487523819,
        valorKmNaoPavimentado: 3.45818786509647,
    },
    "ROTA 14": {
        id:"ROTA 14",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) –  Sítio Capim de Planta, Sítio Travessão, Sítio Abelha, Sítio Gameleira, Sítio Serra do Urubu, Sítio Gameleira, Sítio Travessão, Sítio Lagoa do Caroá. 2. (Manhã- volta Tarde ida) – Lagoa do Caroá, Sítio Travessão, Sítio Gameleira, Sítio Serra do Urubu, Sítio Gameleira, Sítio Abelha, Sítio Travessão, Sitio Capim de planta, Sítio Barreiros do Fabiano, Sítio Travesssão. 3. (Tarde Volta) – Sítio Lagoa do Caroá, Sítio Barreiro do Fabiano, Sítio Travessão.',
        kmPavimentado:0,
        kmNaoPavimentado:82.033,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 15": {
        id:"ROTA 15",
        condutor: "",
        tipo:'VAN',
        placaVeiculo:"",
        rota:'1. (Manhã- ida) – Sítio Malhada, Sítio Macammbinho, Sítio Serrinha, Sítio Carnaiba Velha, Sítio Carnaiba, Sítio Alto da Santa Luzia, Carnaiba. 2. (Manhã-volta Tarde ida) – Carnaiba, Sítio Alto da Santa Luzia, Sítio Carnaiba Velha, Sítio Serrinha, Sítio Mucambinho, Sítio Malhada, Carnaiba. 3. (Tarde volta) – Carnaiba, Sítio Carnaiba Velha, Sítio Serrinha, Sítio Mucambinho, Sítio Malhada.',
        kmPavimentado:14.542,
        kmNaoPavimentado:74.790,
        valorFixo:2206.89735418111,
        valorKmPavimentado: 1.69606438540608,
        valorKmNaoPavimentado: 2.0447192906279,
    },
    "ROTA 16": {},
    "ROTA 17": {},
    "ROTA 18": {},
    "ROTA 19": {},
    "ROTA 20": {},
    "ROTA 21": {},
    "ROTA 22": {},
    "ROTA 23": {},
    "ROTA 24": {},
    "ROTA 25": {},
    "ROTA 26": {},
    "ROTA 27": {},
    "ROTA 28": {},
    "ROTA 29": {},
    "ROTA 30": {},
    "ROTA 31": {},
    "ROTA 32": {},
    "ROTA 33": {}
}